import { homeCarousel } from "./home-carousel"
import type { SiteContent } from "./types"

export const en: SiteContent = {
  locale: "en",
  meta: {
    title: "Ai Labs — Adapt, develop, and learn with AI",
    description:
      "Ai Labs helps companies adapt, develop, and learn with AI through Academy, Agentic, and Aperture. Based in El Salvador.",
  },
  chrome: {
    nav: {
      pillars: [
        { id: "academy", label: "Academy", href: "/academy" },
        { id: "agentic", label: "Agentic", href: "/agentic" },
        { id: "aperture", label: "Aperture", href: "/aperture" },
      ],
      contact: { label: "Contact", href: "#contact" },
      cta: { label: "Talk to us", href: "#contact" },
    },
    footer: {
      brandLine:
        "Ai Labs helps companies adapt, develop, and learn with AI.",
      columns: [
        {
          title: "Pillars",
          links: [
            { label: "Academy", href: "/academy" },
            { label: "Agentic", href: "/agentic" },
            { label: "Aperture", href: "/aperture" },
          ],
        },
        {
          title: "Company",
          links: [
            { label: "Contact", href: "#contact" },
            { label: "ailabs.sv", href: "https://ailabs.sv" },
          ],
        },
        {
          title: "Social",
          links: [],
        },
      ],
      copyright: "© {year} Ai Labs",
    },
  },
  microcopy: {
    loading: "Loading…",
    notFoundTitle: "Page not found",
    notFoundBody: "That page doesn't exist. Head home or talk to us.",
    notFoundCtaHome: "Back home",
    languageSwitch: "ES",
    skipToContent: "Skip to content",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    themeCycle: "Cycle color theme",
    themeToLight: "Switch to light theme",
    themeToDark: "Switch to dark theme",
    themeToSystem: "Switch to system theme",
  },
  home: {
    hero: {
      label: "Practical AI work",
      headline: "Adapt, develop, and learn with AI",
      body: "Academy trains your team, Agentic builds your software, and Aperture connects you to the people and companies building with AI. Based in El Salvador — open beyond.",
      primaryCta: { label: "Get started", href: "#contact" },
      secondaryCta: { label: "See the pillars", href: "#academy" },
      proof: { value: "800+", label: "Builders" },
      builders: [
        { name: "Walter", initial: "W" },
        { name: "Daniela", initial: "D" },
        { name: "Bea", initial: "B" },
        { name: "Saul", initial: "S" },
      ],
      slides: [
        { value: "800+", label: "Builders", icon: "builders" },
        { value: "30+", label: "Events hosted", icon: "events" },
        { value: "8", label: "Active partners", icon: "partners" },
      ],
      mediaSrcs: homeCarousel.hero,
      mediaAlt: "Ai Labs community session",
    },
    about: {
      label: "Why companies come",
      body: "They need AI they can use: train a team, ship a product, or get close to builders already in the tools. We run the sessions and ship the software.",
      stats: [
        { value: "30+", label: "Events hosted" },
        { value: "8", label: "Active partners" },
      ],
      bold: "Adapt means your team can use the tools. Develop means something ships. Learn means practice sticks — not another deck about the future of AI.",
      bridgeLabel: "How it shows up",
      bridge: [
        { title: "Academy", body: "Learning that sticks, in practice." },
        { title: "Agentic", body: "Software and workflows we build with you." },
        {
          title: "Aperture",
          body: "A way into the people and companies building with AI.",
        },
      ],
      mediaSrcs: homeCarousel.about,
      mediaAlt: "Builders collaborating at an Ai Labs event",
      toastTitle: "Session in progress",
      toastMeta: "El Salvador",
    },
    academy: {
      id: "academy",
      index: "01",
      eyebrow: "Learn with us",
      title: "Academy",
      lead: "Trainings, bootcamps, and residencies that teach AI by building with it — not another slide deck.",
      points: [
        {
          title: "For your team",
          body: "Adoption training so people actually use the tools.",
        },
        {
          title: "As a consultancy",
          body: "We scope and run the whole program with you.",
        },
        {
          title: "Open to everyone",
          body: "Public workshops and bootcamps for anyone learning AI.",
        },
      ],
      cta: { label: "Train my team", href: "#contact" },
      mediaSrcs: homeCarousel.features,
      mediaAlt: "Hands-on workshop at Ai Labs",
    },
    agentic: {
      id: "agentic",
      index: "02",
      eyebrow: "Build with us",
      title: "Agentic",
      lead: "Agentic software development, on demand — custom products and AI workflows, built and shipped with you.",
      points: [
        {
          title: "Software products",
          body: "From first version to production, tailored to your problem.",
        },
        {
          title: "AI workflows",
          body: "Automation that fits how your team already works.",
        },
        {
          title: "Built with AI",
          body: "We work the way we teach — agentic and hands-on.",
        },
      ],
      cta: { label: "Scope a build", href: "#contact" },
      mediaSrcs: homeCarousel.about,
      mediaAlt: "Builders shipping software at an Ai Labs session",
    },
    aperture: {
      id: "aperture",
      index: "03",
      eyebrow: "Connect with us",
      title: "Aperture",
      lead: "An innovation hub that connects you to the frontier AI companies we work with — and the 800+ builders around them.",
      voices: [
        {
          quote: "I learn by building.",
          name: "Cristina, CFO at YonJob",
          role: "Builder",
        },
        {
          quote: "Workshops, mentors, and real connection.",
          name: "Cristian, Software Engineer",
          role: "Academy",
        },
        {
          quote: "Great people, real events, one love for tech.",
          name: "Kharen, Design Student",
          role: "Aperture",
        },
      ],
      members: [
        { id: "m-01", initial: "M" },
        { id: "m-02", initial: "R" },
        { id: "m-03", initial: "A" },
        { id: "m-04", initial: "L" },
        { id: "m-05", initial: "S" },
        { id: "m-06", initial: "D" },
        { id: "m-07", initial: "C" },
        { id: "m-08", initial: "J" },
        { id: "m-09", initial: "E" },
        { id: "m-10", initial: "N" },
        { id: "m-11", initial: "V" },
        { id: "m-12", initial: "K" },
        { id: "m-13", initial: "P" },
        { id: "m-14", initial: "T" },
        { id: "m-15", initial: "B" },
        { id: "m-16", initial: "G" },
        { id: "m-17", initial: "H" },
        { id: "m-18", initial: "F" },
        { id: "m-19", initial: "W" },
        { id: "m-20", initial: "Y" },
        { id: "m-21", initial: "Q" },
        { id: "m-22", initial: "Z" },
        { id: "m-23", initial: "U" },
        { id: "m-24", initial: "I" },
        { id: "m-25", initial: "O" },
        { id: "m-26", initial: "X" },
        { id: "m-27", initial: "A" },
        { id: "m-28", initial: "S" },
        { id: "m-29", initial: "M" },
        { id: "m-30", initial: "R" },
        { id: "m-31", initial: "L" },
        { id: "m-32", initial: "D" },
        { id: "m-33", initial: "C" },
        { id: "m-34", initial: "N" },
        { id: "m-35", initial: "J" },
        { id: "m-36", initial: "E" },
        { id: "m-37", initial: "P" },
        { id: "m-38", initial: "V" },
        { id: "m-39", initial: "T" },
        { id: "m-40", initial: "K" },
        { id: "m-41", initial: "B" },
        { id: "m-42", initial: "G" },
        { id: "m-43", initial: "H" },
        { id: "m-44", initial: "F" },
        { id: "m-45", initial: "W" },
        { id: "m-46", initial: "Y" },
        { id: "m-47", initial: "Q" },
        { id: "m-48", initial: "Z" },
        { id: "m-49", initial: "U" },
        { id: "m-50", initial: "I" },
        { id: "m-51", initial: "O" },
        { id: "m-52", initial: "X" },
        { id: "m-53", initial: "M" },
        { id: "m-54", initial: "A" },
        { id: "m-55", initial: "R" },
        { id: "m-56", initial: "S" },
        { id: "m-57", initial: "L" },
        { id: "m-58", initial: "D" },
        { id: "m-59", initial: "C" },
        { id: "m-60", initial: "N" },
        { id: "m-61", initial: "J" },
        { id: "m-62", initial: "E" },
        { id: "m-63", initial: "P" },
        { id: "m-64", initial: "V" },
      ],
      stat: { value: "800+", label: "Builders in the community" },
      quote:
        "We're ambassadors for the companies pushing AI forward. Aperture is how that access reaches you — and how you meet the people already building.",
      attribution: "Ai Labs",
      cta: { label: "Meet the community", href: "#contact" },
    },
    contact: {
      title: "Tell us what you need",
      lead: "Bring Ai Labs to your team. Say if you need training, software work, or a way into the community — we’ll follow up.",
      nameLabel: "Name",
      namePlaceholder: "Your name",
      emailLabel: "Email",
      emailPlaceholder: "you@company.com",
      companyLabel: "Company",
      companyPlaceholder: "Company name",
      interestLabel: "Where should we start?",
      interestOptions: [
        { value: "academy", label: "Academy" },
        { value: "agentic", label: "Agentic" },
        { value: "aperture", label: "Aperture" },
      ],
      messageLabel: "What are you working on?",
      messagePlaceholder:
        "Training, a build, community access — whatever you're exploring",
      submit: "Send message",
      submitting: "Sending…",
      success: "Thanks — we’ll get back to you soon.",
      error: "Something went wrong. Try again or email us.",
    },
  },
  redeem: {
    metaTitle: "Redeem credits",
    eventLabel: "Event",
    howItWorksLabel: "How it works",
    steps: [
      { title: "Sign in", body: "Use your event email" },
      { title: "Get verified", body: "We check the guest list" },
      { title: "Copy your code", body: "Redeem in seconds" },
    ],
    poweredBy: "An Ai Labs event",
    signInPrompt:
      "Sign in with the same email you used to register for this event.",
    signInCta: "Sign in to claim",
    claimCta: "Claim credits",
    claiming: "Claiming…",
    signedInAs: "Signed in as {email}",
    signOutCta: "Sign out",
    yourCode: "Your code",
    yourCodes: "Your codes",
    alreadyRedeemed: "You already claimed these credits for this event.",
    copyCode: "Copy",
    copied: "Copied",
    openCode: "Open",
    invalidTitle: "Link not found",
    invalidBody:
      "This redeem link is invalid. Check the URL from your event host.",
    inactiveTitle: "Redemption closed",
    inactiveBody: "This event is no longer accepting credit claims.",
    notEligibleTitle: "Email not on the list",
    notEligibleBody:
      "Your signed-in email isn’t registered for this event. Use the email from your Luma registration.",
    soldOutTitle: "Codes unavailable",
    soldOutBody:
      "All codes for this event have been claimed. Contact the event host.",
    noVerifiedEmailTitle: "Verify your email",
    noVerifiedEmailBody:
      "Your account needs a verified email before you can claim credits.",
    missingCodeTitle: "Missing code",
    missingCodeBody: "Open the full redeem link that includes ?code=…",
    poolLabels: {
      CURSOR: "Cursor",
      CODEX: "Codex",
      OPENAI: "OpenAI Platform",
    },
    products: {
      cursor: {
        title: "Cursor credits",
        blurb: "Claim your Cursor promo code from this Ai Labs event.",
      },
      codex: {
        title: "Codex credits",
        blurb: "Claim your Codex promo code from this Ai Labs event.",
      },
      openai: {
        title: "OpenAI Platform credits",
        blurb: "Claim your OpenAI Platform promo code from this Ai Labs event.",
      },
      codexOpenai: {
        title: "Codex + OpenAI Platform credits",
        blurb:
          "Claim both your Codex and OpenAI Platform promo codes from this event.",
      },
    },
  },
}
