import type { SiteContent } from "./types"

export const en: SiteContent = {
  locale: "en",
  meta: {
    title: "Ai Labs — Adapt, develop, and learn with AI",
    description:
      "Ai Labs helps companies adapt, develop, and learn with AI through Academy, Agentic, and Aperture. Based in El Salvador.",
  },
  chrome: {
    nav: {
      pillars: [
        { id: "academy", label: "Academy", href: "/academy" },
        { id: "agentic", label: "Agentic", href: "/agentic" },
        { id: "aperture", label: "Aperture", href: "/aperture" },
      ],
      contact: { label: "Contact", href: "#contact" },
      cta: { label: "Talk to us", href: "#contact" },
    },
    footer: {
      brandLine:
        "Ai Labs helps companies adapt, develop, and learn with AI.",
      columns: [
        {
          title: "Pillars",
          links: [
            { label: "Academy", href: "/academy" },
            { label: "Agentic", href: "/agentic" },
            { label: "Aperture", href: "/aperture" },
          ],
        },
        {
          title: "Company",
          links: [
            { label: "Contact", href: "#contact" },
            { label: "ailabs.sv", href: "https://ailabs.sv" },
          ],
        },
        {
          title: "Social",
          links: [],
        },
      ],
      copyright: "© {year} Ai Labs",
    },
  },
  microcopy: {
    loading: "Loading…",
    notFoundTitle: "Page not found",
    notFoundBody: "That page doesn't exist. Head home or talk to us.",
    notFoundCtaHome: "Back home",
    languageSwitch: "ES",
    skipToContent: "Skip to content",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    themeCycle: "Cycle color theme",
    themeToLight: "Switch to light theme",
    themeToDark: "Switch to dark theme",
    themeToSystem: "Switch to system theme",
  },
  home: {
    hero: {
      label: "Practical AI work",
      headline: "Adapt, develop, and learn with AI",
      body: "We help companies through teaching, software work, and a builder community. Based in El Salvador — open beyond.",
      primaryCta: { label: "Talk to us", href: "#contact" },
      secondaryCta: { label: "Explore the pillars", href: "#pillars" },
      proof: { value: "700+", label: "Builders" },
      slides: [
        { value: "700+", label: "Builders" },
        { value: "30+", label: "Events hosted" },
        { value: "8", label: "Active partners" },
      ],
      mediaSrc: "/carousel/1.webp",
      mediaAlt: "Ai Labs community session",
    },
    about: {
      label: "Why companies come",
      body: "They need AI they can use: train a team, ship a product, or get close to builders already in the tools. We run the sessions and ship the software.",
      stats: [
        { value: "30+", label: "Events hosted" },
        { value: "8", label: "Active partners" },
      ],
      bold: "Adapt means your team can use the tools. Develop means something ships. Learn means practice sticks — not another deck about the future of AI.",
      mediaSrc: "/carousel/2.webp",
      mediaAlt: "Builders collaborating at an Ai Labs event",
      toastTitle: "Session in progress",
      toastMeta: "El Salvador",
    },
    features: {
      label: "How we work",
      headline: "Three ways to work with us",
      cta: { label: "Talk to us", href: "#contact" },
      showcaseImageSrc: "/carousel/3.webp",
      showcaseImageAlt: "Hands-on workshop at Ai Labs",
      accordion: [
        {
          id: "academy",
          title: "Academy",
          subtitle: "Learn with us",
          body: "Consultancies, workshops, bootcamps, and residencies so people learn AI in practice.",
        },
        {
          id: "agentic",
          title: "Agentic",
          subtitle: "Build with us",
          body: "Software on demand, plus workflows and automation, done with AI.",
        },
        {
          id: "aperture",
          title: "Aperture",
          subtitle: "Connect with us",
          body: "A hub that links people, profiles we work with, and the companies we partner with.",
        },
      ],
      cards: [
        {
          id: "academy",
          title: "Academy",
          body: "For teams, founders, and students who need practice, not lectures.",
          cta: { label: "See Academy", href: "/academy" },
        },
        {
          id: "agentic",
          title: "Agentic",
          body: "For teams that need something usable, not another prototype deck.",
          cta: { label: "See Agentic", href: "/agentic" },
        },
        {
          id: "aperture",
          title: "Aperture",
          body: "For people and companies who want the room, not a mailing list.",
          cta: { label: "See Aperture", href: "/aperture" },
        },
      ],
    },
    partner: {
      headline: "What it means to be here",
      lead: "Practice, people who ship, and a way in — the room the work comes from.",
      voices: [
        { quote: "I learn by building with others", role: "Builder" },
        { quote: "Sessions that stick past the workshop", role: "Academy" },
        { quote: "Real intros, not a newsletter", role: "Aperture" },
      ],
      members: [
        { id: "m-01", initial: "M" },
        { id: "m-02", initial: "R" },
        { id: "m-03", initial: "A" },
        { id: "m-04", initial: "L" },
        { id: "m-05", initial: "S" },
        { id: "m-06", initial: "D" },
        { id: "m-07", initial: "C" },
        { id: "m-08", initial: "J" },
        { id: "m-09", initial: "E" },
        { id: "m-10", initial: "N" },
        { id: "m-11", initial: "V" },
        { id: "m-12", initial: "K" },
        { id: "m-13", initial: "P" },
        { id: "m-14", initial: "T" },
        { id: "m-15", initial: "B" },
        { id: "m-16", initial: "G" },
        { id: "m-17", initial: "H" },
        { id: "m-18", initial: "F" },
        { id: "m-19", initial: "W" },
        { id: "m-20", initial: "Y" },
        { id: "m-21", initial: "Q" },
        { id: "m-22", initial: "Z" },
        { id: "m-23", initial: "U" },
        { id: "m-24", initial: "I" },
        { id: "m-25", initial: "O" },
        { id: "m-26", initial: "X" },
        { id: "m-27", initial: "A" },
        { id: "m-28", initial: "S" },
        { id: "m-29", initial: "M" },
        { id: "m-30", initial: "R" },
        { id: "m-31", initial: "L" },
        { id: "m-32", initial: "D" },
        { id: "m-33", initial: "C" },
        { id: "m-34", initial: "N" },
        { id: "m-35", initial: "J" },
        { id: "m-36", initial: "E" },
        { id: "m-37", initial: "P" },
        { id: "m-38", initial: "V" },
        { id: "m-39", initial: "T" },
        { id: "m-40", initial: "K" },
        { id: "m-41", initial: "B" },
        { id: "m-42", initial: "G" },
        { id: "m-43", initial: "H" },
        { id: "m-44", initial: "F" },
        { id: "m-45", initial: "W" },
        { id: "m-46", initial: "Y" },
        { id: "m-47", initial: "Q" },
        { id: "m-48", initial: "Z" },
        { id: "m-49", initial: "U" },
        { id: "m-50", initial: "I" },
        { id: "m-51", initial: "O" },
        { id: "m-52", initial: "X" },
        { id: "m-53", initial: "M" },
        { id: "m-54", initial: "A" },
        { id: "m-55", initial: "R" },
        { id: "m-56", initial: "S" },
        { id: "m-57", initial: "L" },
        { id: "m-58", initial: "D" },
        { id: "m-59", initial: "C" },
        { id: "m-60", initial: "N" },
        { id: "m-61", initial: "J" },
        { id: "m-62", initial: "E" },
        { id: "m-63", initial: "P" },
        { id: "m-64", initial: "V" },
      ],
    },
    trust: {
      label: "Proof",
      headline: "Why teams work with us",
      stat: { value: "700+", label: "Builders in the community" },
      quote:
        "We combine practical learning, software work, and ecosystem access. Most alternatives only cover one of those.",
      attribution: "Ai Labs",
      portraitSrc: "/carousel/5.webp",
      portraitAlt: "Ai Labs community member at an event",
    },
    contact: {
      title: "Talk to us",
      lead: "Tell us what you need — training, software, or a way into the community. We’ll follow up.",
      nameLabel: "Name",
      emailLabel: "Email",
      companyLabel: "Company",
      interestLabel: "What are you interested in?",
      interestOptions: [
        { value: "academy", label: "Academy" },
        { value: "agentic", label: "Agentic" },
        { value: "aperture", label: "Aperture" },
      ],
      messageLabel: "Message",
      submit: "Send message",
      submitting: "Sending…",
      success: "Thanks — we’ll get back to you soon.",
      error: "Something went wrong. Try again or email us.",
    },
  },
  redeem: {
    metaTitle: "Redeem credits",
    eventLabel: "Event",
    signInPrompt:
      "Sign in with the same email you used to register for this event.",
    signInCta: "Sign in to claim",
    claimCta: "Claim credits",
    claiming: "Claiming…",
    signedInAs: "Signed in as {email}",
    yourCodes: "Your codes",
    alreadyRedeemed: "You already claimed these credits for this event.",
    copyCode: "Copy",
    copied: "Copied",
    invalidTitle: "Link not found",
    invalidBody:
      "This redeem link is invalid. Check the URL from your event host.",
    inactiveTitle: "Redemption closed",
    inactiveBody: "This event is no longer accepting credit claims.",
    notEligibleTitle: "Email not on the list",
    notEligibleBody:
      "Your signed-in email isn’t registered for this event. Use the email from your Luma registration.",
    soldOutTitle: "Codes unavailable",
    soldOutBody:
      "All codes for this event have been claimed. Contact the event host.",
    noVerifiedEmailTitle: "Verify your email",
    noVerifiedEmailBody:
      "Your account needs a verified email before you can claim credits.",
    missingCodeTitle: "Missing code",
    missingCodeBody: "Open the full redeem link that includes ?code=…",
    poolLabels: {
      CURSOR: "Cursor",
      CODEX: "Codex",
      OPENAI: "OpenAI Platform",
    },
    products: {
      cursor: {
        title: "Cursor credits",
        blurb: "Claim your Cursor promo code from this Ai Labs event.",
      },
      codex: {
        title: "Codex credits",
        blurb: "Claim your Codex promo code from this Ai Labs event.",
      },
      openai: {
        title: "OpenAI Platform credits",
        blurb: "Claim your OpenAI Platform promo code from this Ai Labs event.",
      },
      codexOpenai: {
        title: "Codex + OpenAI Platform credits",
        blurb:
          "Claim both your Codex and OpenAI Platform promo codes from this event.",
      },
    },
  },
}
