import { homeCarousel } from "./home-carousel"
import type { SiteContent } from "./types"

export const es: SiteContent = {
  locale: "es",
  meta: {
    title: "Ai Labs — Adáptate, desarrolla y aprende con IA",
    description:
      "Ai Labs es una empresa de IA en El Salvador que ayuda a las empresas a adaptarse, desarrollar y aprender con IA a través de Academy, Agentic y Aperture.",
  },
  chrome: {
    nav: {
      pillars: [
        { id: "academy", label: "Academy", href: "#academy" },
        { id: "agentic", label: "Agentic", href: "#agentic" },
        { id: "aperture", label: "Aperture", href: "#aperture" },
      ],
      community: { label: "Comunidad", href: "/community" },
      contact: { label: "Contacto", href: "#contact" },
      cta: { label: "Hablemos", href: "#contact" },
    },
    footer: {
      brandLine:
        "Ai Labs ayuda a las empresas a adaptarse, desarrollar y aprender con IA.",
      columns: [
        {
          title: "Pilares",
          links: [
            { label: "Academy", href: "#academy" },
            { label: "Agentic", href: "#agentic" },
            { label: "Aperture", href: "#aperture" },
          ],
        },
        {
          title: "Compañía",
          links: [
            { label: "Comunidad", href: "/community" },
            { label: "Contacto", href: "#contact" },
            { label: "ailabs.sv", href: "https://ailabs.sv" },
          ],
        },
        {
          title: "Redes",
          links: [],
        },
      ],
      copyright: "© {year} Ai Labs",
    },
  },
  microcopy: {
    loading: "Cargando…",
    notFoundTitle: "Página no encontrada",
    notFoundBody: "Esa página no existe. Vuelve al inicio o háblanos.",
    notFoundCtaHome: "Ir al inicio",
    languageSwitch: "EN",
    skipToContent: "Saltar al contenido",
    menuOpen: "Abrir menú",
    menuClose: "Cerrar menú",
    themeCycle: "Cambiar tema de color",
    themeToLight: "Cambiar a tema claro",
    themeToDark: "Cambiar a tema oscuro",
    themeToSystem: "Cambiar a tema del sistema",
  },
  home: {
    hero: {
      label: "IA práctica",
      headline: "Adáptate, desarrolla y aprende con IA",
      body: "Academy forma a tu equipo, Agentic construye tu software y Aperture te conecta con builders — desde El Salvador, y más allá.",
      primaryCta: { label: "Empecemos", href: "#contact" },
      secondaryCta: { label: "Conoce los pilares", href: "#academy" },
      proof: { value: "800+", label: "Builders" },
      builders: [
        { name: "Walter", initial: "W" },
        { name: "Daniela", initial: "D" },
        { name: "Bea", initial: "B" },
        { name: "Saúl", initial: "S" },
      ],
      slides: [
        { value: "800+", label: "Builders", icon: "builders" },
        { value: "40+", label: "Eventos realizados", icon: "events" },
        { value: "8", label: "Partners activos", icon: "partners" },
      ],
      mediaSrcs: homeCarousel.hero,
      mediaAlt: "Sesión de comunidad de Ai Labs",
    },
    trust: {
      label: "Compañías con las que trabajamos",
      logos: [
        { id: "cursor", name: "Cursor" },
        { id: "codex", name: "Codex" },
        { id: "openai", name: "OpenAI" },
        { id: "claude", name: "Claude" },
        { id: "mistral", name: "Mistral" },
        { id: "elevenlabs", name: "ElevenLabs" },
        { id: "notion", name: "Notion" },
      ],
    },
    about: {
      label: "Por qué vienen las empresas",
      body: "Necesitan IA que puedan usar: formar un equipo, lanzar un producto, o acercarse a builders que ya usan las herramientas. Corremos las sesiones y entregamos el software.",
      stats: [
        { value: "40+", label: "Eventos realizados" },
        { value: "8", label: "Partners activos" },
      ],
      bold: "Adaptarse es que tu equipo use las herramientas. Desarrollar es que algo se lance. Aprender es que la práctica quede — no otro deck sobre “el futuro de la IA.”",
      bridgeLabel: "Cómo se ve en la práctica",
      bridge: [
        { title: "Academy", body: "Aprendizaje que queda, en la práctica." },
        { title: "Agentic", body: "Software y flujos que construimos contigo." },
        {
          title: "Aperture",
          body: "Una puerta a las personas y empresas que construyen con IA.",
        },
      ],
      mediaSrcs: homeCarousel.about,
      mediaAlt: "Builders colaborando en un evento de Ai Labs",
      toastTitle: "Sesión en curso",
      toastMeta: "El Salvador",
    },
    academy: {
      id: "academy",
      index: "01",
      eyebrow: "Aprende con nosotros",
      title: "Academy",
      lead: "Formaciones, bootcamps y residencias que enseñan IA construyendo con ella — no otro slide deck.",
      points: [
        {
          title: "Para tu equipo",
          body: "Formación de adopción para que la gente use las herramientas de verdad.",
        },
        {
          title: "Como consultoría",
          body: "Diseñamos y corremos todo el programa contigo.",
        },
        {
          title: "Abierto a todos",
          body: "Talleres y bootcamps públicos para quien esté aprendiendo IA.",
        },
      ],
      cta: { label: "Formar a mi equipo", href: "#contact" },
      mediaSrcs: homeCarousel.features,
      mediaAlt: "Taller práctico en Ai Labs",
    },
    agentic: {
      id: "agentic",
      index: "02",
      eyebrow: "Construye con nosotros",
      title: "Agentic",
      lead: "Desarrollo de software agéntico, bajo demanda — productos y flujos de IA a medida, construidos y lanzados contigo.",
      points: [
        {
          title: "Productos de software",
          body: "De la primera versión a producción, a la medida de tu problema.",
        },
        {
          title: "Flujos con IA",
          body: "Automatización que encaja con cómo ya trabaja tu equipo.",
        },
        {
          title: "Hecho con IA",
          body: "Trabajamos como enseñamos — agéntico y práctico.",
        },
      ],
      cta: { label: "Definir un proyecto", href: "#contact" },
      mediaSrcs: homeCarousel.about,
      mediaAlt: "Builders lanzando software en una sesión de Ai Labs",
    },
    aperture: {
      id: "aperture",
      index: "03",
      eyebrow: "Conéctate con nosotros",
      title: "Aperture",
      lead: "Un hub de innovación que te conecta con las empresas de IA de frontera con las que trabajamos — y los 800+ builders a su alrededor.",
      voices: [
        {
          quote: "Aprendo construyendo.",
          name: "Cristina, CFO en YonJob",
          role: "Builder",
        },
        {
          quote: "Talleres, mentores y conexión real.",
          name: "Cristian, Ingeniero en Sistemas",
          role: "Academy",
        },
        {
          quote: "Gente buena, eventos reales, un amor por la tecnología.",
          name: "Kharen, Estudiante de Diseño",
          role: "Aperture",
        },
      ],
      members: [
        { id: "m-01", initial: "M" },
        { id: "m-02", initial: "R" },
        { id: "m-03", initial: "A" },
        { id: "m-04", initial: "L" },
        { id: "m-05", initial: "S" },
        { id: "m-06", initial: "D" },
        { id: "m-07", initial: "C" },
        { id: "m-08", initial: "J" },
        { id: "m-09", initial: "E" },
        { id: "m-10", initial: "N" },
        { id: "m-11", initial: "V" },
        { id: "m-12", initial: "K" },
        { id: "m-13", initial: "P" },
        { id: "m-14", initial: "T" },
        { id: "m-15", initial: "B" },
        { id: "m-16", initial: "G" },
        { id: "m-17", initial: "H" },
        { id: "m-18", initial: "F" },
        { id: "m-19", initial: "W" },
        { id: "m-20", initial: "Y" },
        { id: "m-21", initial: "Q" },
        { id: "m-22", initial: "Z" },
        { id: "m-23", initial: "U" },
        { id: "m-24", initial: "I" },
        { id: "m-25", initial: "O" },
        { id: "m-26", initial: "X" },
        { id: "m-27", initial: "A" },
        { id: "m-28", initial: "S" },
        { id: "m-29", initial: "M" },
        { id: "m-30", initial: "R" },
        { id: "m-31", initial: "L" },
        { id: "m-32", initial: "D" },
        { id: "m-33", initial: "C" },
        { id: "m-34", initial: "N" },
        { id: "m-35", initial: "J" },
        { id: "m-36", initial: "E" },
        { id: "m-37", initial: "P" },
        { id: "m-38", initial: "V" },
        { id: "m-39", initial: "T" },
        { id: "m-40", initial: "K" },
        { id: "m-41", initial: "B" },
        { id: "m-42", initial: "G" },
        { id: "m-43", initial: "H" },
        { id: "m-44", initial: "F" },
        { id: "m-45", initial: "W" },
        { id: "m-46", initial: "Y" },
        { id: "m-47", initial: "Q" },
        { id: "m-48", initial: "Z" },
        { id: "m-49", initial: "U" },
        { id: "m-50", initial: "I" },
        { id: "m-51", initial: "O" },
        { id: "m-52", initial: "X" },
        { id: "m-53", initial: "M" },
        { id: "m-54", initial: "A" },
        { id: "m-55", initial: "R" },
        { id: "m-56", initial: "S" },
        { id: "m-57", initial: "L" },
        { id: "m-58", initial: "D" },
        { id: "m-59", initial: "C" },
        { id: "m-60", initial: "N" },
        { id: "m-61", initial: "J" },
        { id: "m-62", initial: "E" },
        { id: "m-63", initial: "P" },
        { id: "m-64", initial: "V" },
      ],
      stat: { value: "800+", label: "Builders en la comunidad" },
      quote:
        "Somos embajadores de las empresas que empujan la IA. Aperture es cómo ese acceso llega a ti — y cómo conoces a quienes ya están construyendo.",
      attribution: "Ai Labs",
      cta: { label: "Conocer la comunidad", href: "#contact" },
    },
    contact: {
      title: "Cuéntanos qué necesitas",
      lead: "Trae Ai Labs a tu equipo. Di si necesitas formación, software, o conectar con la comunidad — te respondemos.",
      nameLabel: "Nombre",
      namePlaceholder: "Tu nombre",
      emailLabel: "Correo",
      emailPlaceholder: "tu@empresa.com",
      companyLabel: "Empresa",
      companyPlaceholder: "Nombre de la empresa",
      interestLabel: "¿Por dónde empezamos?",
      interestOptions: [
        { value: "academy", label: "Academy" },
        { value: "agentic", label: "Agentic" },
        { value: "aperture", label: "Aperture" },
      ],
      messageLabel: "¿En qué estás trabajando?",
      messagePlaceholder:
        "Formación, un build, acceso a la comunidad — lo que estés explorando",
      submit: "Enviar mensaje",
      submitting: "Enviando…",
      success: "Gracias — te contactamos pronto.",
      error: "Algo falló. Intenta de nuevo o escríbenos.",
    },
  },
  redeem: {
    metaTitle: "Canjear créditos",
    eventLabel: "Evento",
    howItWorksLabel: "Cómo funciona",
    steps: [
      { title: "Inicia sesión", body: "Usa el correo de tu evento" },
      { title: "Verifícate", body: "Revisamos la lista de invitados" },
      { title: "Copia tu código", body: "Canjea en segundos" },
    ],
    poweredBy: "Un evento de Ai Labs",
    signInPrompt:
      "Inicia sesión con el mismo correo con el que te registraste al evento.",
    signInCta: "Iniciar sesión para canjear",
    claimCta: "Canjear créditos",
    claiming: "Canjeando…",
    signedInAs: "Sesión iniciada como {email}",
    signOutCta: "Cerrar sesión",
    yourCode: "Tu código",
    yourCodes: "Tus códigos",
    alreadyRedeemed: "Ya canjeaste estos créditos para este evento.",
    copyCode: "Copiar",
    copied: "Copiado",
    openCode: "Abrir",
    invalidTitle: "Enlace no encontrado",
    invalidBody:
      "Este enlace de canje no es válido. Revisa la URL del organizador.",
    inactiveTitle: "Canje cerrado",
    inactiveBody: "Este evento ya no acepta canjes de créditos.",
    notEligibleTitle: "Correo no está en la lista",
    notEligibleBody:
      "El correo de tu sesión no está registrado en este evento. Usa el de tu registro en Luma.",
    soldOutTitle: "Códigos agotados",
    soldOutBody:
      "Todos los códigos de este evento ya fueron canjeados. Contacta al organizador.",
    noVerifiedEmailTitle: "Verifica tu correo",
    noVerifiedEmailBody:
      "Tu cuenta necesita un correo verificado antes de canjear créditos.",
    missingCodeTitle: "Falta el código",
    missingCodeBody: "Abre el enlace completo que incluye ?code=…",
    qrCta: "QR",
    qrTitle: "Escanea para abrir",
    qrBody: "Escanea este código para abrir esta página en otro dispositivo.",
    poolLabels: {
      CURSOR: "Cursor",
      CODEX: "Codex",
      OPENAI: "OpenAI Platform",
    },
    products: {
      cursor: {
        title: "Créditos de Cursor",
        blurb: "Canjea tu código de Cursor de este evento de Ai Labs.",
      },
      codex: {
        title: "Créditos de Codex",
        blurb: "Canjea tu código de Codex de este evento de Ai Labs.",
      },
      openai: {
        title: "Créditos de OpenAI Platform",
        blurb:
          "Canjea tu código de OpenAI Platform de este evento de Ai Labs.",
      },
      codexOpenai: {
        title: "Créditos de Codex + OpenAI Platform",
        blurb:
          "Canjea tus códigos de Codex y OpenAI Platform de este evento.",
      },
    },
  },
  community: {
    metaTitle: "Únete a la comunidad",
    metaDescription:
      "Únete a la comunidad de WhatsApp de Ai Labs — builders, eventos e IA práctica en El Salvador.",
    label: "Comunidad",
    headline: "Únete a la comunidad de WhatsApp de Ai Labs",
    body: "Mantente cerca de eventos, talleres y builders que adaptan el trabajo real con IA.",
    joinPrompt: "Builders, eventos y talleres — unirte es gratis.",
    joinCta: "Unirme en WhatsApp",
    joinHint: "Abre WhatsApp · puede pedir aprobación",
    joinHref: "https://chat.whatsapp.com/Ga8mG1fqDM9C0ryxAw1eIj",
    howItWorksLabel: "Cómo funciona",
    steps: [
      { title: "Abre la invitación", body: "Toca Unirme en WhatsApp" },
      {
        title: "Solicita unirte",
        body: "WhatsApp puede pedir aprobación",
      },
      { title: "Saluda", body: "Preséntate y sigue la conversación" },
    ],
    qrCta: "QR",
    qrTitle: "Escanea para abrir",
    qrBody: "Escanea este código para abrir esta página en otro dispositivo.",
  },
}
