import type { SiteContent } from "./types"

export const es: SiteContent = {
  locale: "es",
  meta: {
    title: "Ai Labs — Adáptate, desarrolla y aprende con IA",
    description:
      "Ai Labs ayuda a las empresas a adaptarse, desarrollar y aprender con IA a través de Academy, Agentic y Aperture. Con base en El Salvador.",
  },
  chrome: {
    nav: {
      pillars: [
        { id: "academy", label: "Academy", href: "/academy" },
        { id: "agentic", label: "Agentic", href: "/agentic" },
        { id: "aperture", label: "Aperture", href: "/aperture" },
      ],
      contact: { label: "Contacto", href: "#contact" },
      cta: { label: "Hablemos", href: "#contact" },
    },
    footer: {
      brandLine:
        "Ai Labs ayuda a las empresas a adaptarse, desarrollar y aprender con IA.",
      columns: [
        {
          title: "Pilares",
          links: [
            { label: "Academy", href: "/academy" },
            { label: "Agentic", href: "/agentic" },
            { label: "Aperture", href: "/aperture" },
          ],
        },
        {
          title: "Compañía",
          links: [
            { label: "Contacto", href: "#contact" },
            { label: "ailabs.sv", href: "https://ailabs.sv" },
          ],
        },
        {
          title: "Redes",
          links: [],
        },
      ],
      copyright: "© {year} Ai Labs",
    },
  },
  microcopy: {
    loading: "Cargando…",
    notFoundTitle: "Página no encontrada",
    notFoundBody: "Esa página no existe. Vuelve al inicio o háblanos.",
    notFoundCtaHome: "Ir al inicio",
    languageSwitch: "EN",
    skipToContent: "Saltar al contenido",
    menuOpen: "Abrir menú",
    menuClose: "Cerrar menú",
    themeCycle: "Cambiar tema de color",
    themeToLight: "Cambiar a tema claro",
    themeToDark: "Cambiar a tema oscuro",
    themeToSystem: "Cambiar a tema del sistema",
  },
  home: {
    hero: {
      label: "IA práctica",
      headline: "Adáptate, desarrolla y aprende con IA",
      body: "Ayudamos a empresas con formación, desarrollo de software y una comunidad de builders. Con base en El Salvador — y más allá.",
      primaryCta: { label: "Hablemos", href: "#contact" },
      secondaryCta: { label: "Conoce los pilares", href: "#pillars" },
      proof: { value: "700+", label: "Builders" },
      slides: [
        { value: "700+", label: "Builders", icon: "builders" },
        { value: "30+", label: "Eventos realizados", icon: "events" },
        { value: "8", label: "Partners activos", icon: "partners" },
      ],
      mediaSrc: "/carousel/1.webp",
      mediaAlt: "Sesión de comunidad de Ai Labs",
    },
    about: {
      label: "Por qué vienen las empresas",
      body: "Necesitan IA que puedan usar: formar un equipo, lanzar un producto, o acercarse a builders que ya usan las herramientas. Corremos las sesiones y entregamos el software.",
      stats: [
        { value: "30+", label: "Eventos realizados" },
        { value: "8", label: "Partners activos" },
      ],
      bold: "Adaptarse es que tu equipo use las herramientas. Desarrollar es que algo se lance. Aprender es que la práctica quede — no otro deck sobre “el futuro de la IA.”",
      mediaSrc: "/carousel/2.webp",
      mediaAlt: "Builders colaborando en un evento de Ai Labs",
      toastTitle: "Sesión en curso",
      toastMeta: "El Salvador",
    },
    features: {
      label: "Cómo trabajamos",
      headline: "Tres formas de trabajar con nosotros",
      cta: { label: "Hablemos", href: "#contact" },
      showcaseImageSrc: "/carousel/3.webp",
      showcaseImageAlt: "Taller práctico en Ai Labs",
      accordion: [
        {
          id: "academy",
          title: "Academy",
          subtitle: "Aprende con nosotros",
          body: "Consultorías, talleres, bootcamps y residencias para aprender IA en la práctica.",
        },
        {
          id: "agentic",
          title: "Agentic",
          subtitle: "Construye con nosotros",
          body: "Software bajo demanda, más flujos y automatización, con IA.",
        },
        {
          id: "aperture",
          title: "Aperture",
          subtitle: "Conéctate con nosotros",
          body: "Un hub que conecta personas, perfiles con los que trabajamos y las empresas con las que hacemos partnership.",
        },
      ],
    },
    partner: {
      headline: "Lo que significa estar aquí",
      lead: "Práctica, gente que shippea y una puerta de entrada — el cuarto de donde sale el trabajo.",
      voices: [
        { quote: "Aprendo construyendo con otros", role: "Builder" },
        { quote: "Sesiones que quedan después del taller", role: "Academy" },
        { quote: "Intros reales, no un newsletter", role: "Aperture" },
      ],
      members: [
        { id: "m-01", initial: "M" },
        { id: "m-02", initial: "R" },
        { id: "m-03", initial: "A" },
        { id: "m-04", initial: "L" },
        { id: "m-05", initial: "S" },
        { id: "m-06", initial: "D" },
        { id: "m-07", initial: "C" },
        { id: "m-08", initial: "J" },
        { id: "m-09", initial: "E" },
        { id: "m-10", initial: "N" },
        { id: "m-11", initial: "V" },
        { id: "m-12", initial: "K" },
        { id: "m-13", initial: "P" },
        { id: "m-14", initial: "T" },
        { id: "m-15", initial: "B" },
        { id: "m-16", initial: "G" },
        { id: "m-17", initial: "H" },
        { id: "m-18", initial: "F" },
        { id: "m-19", initial: "W" },
        { id: "m-20", initial: "Y" },
        { id: "m-21", initial: "Q" },
        { id: "m-22", initial: "Z" },
        { id: "m-23", initial: "U" },
        { id: "m-24", initial: "I" },
        { id: "m-25", initial: "O" },
        { id: "m-26", initial: "X" },
        { id: "m-27", initial: "A" },
        { id: "m-28", initial: "S" },
        { id: "m-29", initial: "M" },
        { id: "m-30", initial: "R" },
        { id: "m-31", initial: "L" },
        { id: "m-32", initial: "D" },
        { id: "m-33", initial: "C" },
        { id: "m-34", initial: "N" },
        { id: "m-35", initial: "J" },
        { id: "m-36", initial: "E" },
        { id: "m-37", initial: "P" },
        { id: "m-38", initial: "V" },
        { id: "m-39", initial: "T" },
        { id: "m-40", initial: "K" },
        { id: "m-41", initial: "B" },
        { id: "m-42", initial: "G" },
        { id: "m-43", initial: "H" },
        { id: "m-44", initial: "F" },
        { id: "m-45", initial: "W" },
        { id: "m-46", initial: "Y" },
        { id: "m-47", initial: "Q" },
        { id: "m-48", initial: "Z" },
        { id: "m-49", initial: "U" },
        { id: "m-50", initial: "I" },
        { id: "m-51", initial: "O" },
        { id: "m-52", initial: "X" },
        { id: "m-53", initial: "M" },
        { id: "m-54", initial: "A" },
        { id: "m-55", initial: "R" },
        { id: "m-56", initial: "S" },
        { id: "m-57", initial: "L" },
        { id: "m-58", initial: "D" },
        { id: "m-59", initial: "C" },
        { id: "m-60", initial: "N" },
        { id: "m-61", initial: "J" },
        { id: "m-62", initial: "E" },
        { id: "m-63", initial: "P" },
        { id: "m-64", initial: "V" },
      ],
    },
    trust: {
      label: "Prueba",
      headline: "Por qué trabajan con nosotros",
      stat: { value: "700+", label: "Builders en la comunidad" },
      quote:
        "Combinamos aprendizaje práctico, trabajo de software y acceso al ecosistema. La mayoría de alternativas solo cubre una de esas partes.",
      attribution: "Ai Labs",
      portraitSrc: "/carousel/5.webp",
      portraitAlt: "Miembro de la comunidad Ai Labs en un evento",
    },
    contact: {
      title: "Hablemos",
      lead: "Cuéntanos qué necesitas: formación, software, o conectar con la comunidad. Te respondemos.",
      nameLabel: "Nombre",
      emailLabel: "Correo",
      companyLabel: "Empresa",
      interestLabel: "¿En qué te interesa?",
      interestOptions: [
        { value: "academy", label: "Academy" },
        { value: "agentic", label: "Agentic" },
        { value: "aperture", label: "Aperture" },
      ],
      messageLabel: "Mensaje",
      submit: "Enviar mensaje",
      submitting: "Enviando…",
      success: "Gracias — te contactamos pronto.",
      error: "Algo falló. Intenta de nuevo o escríbenos.",
    },
  },
  redeem: {
    metaTitle: "Canjear créditos",
    eventLabel: "Evento",
    signInPrompt:
      "Inicia sesión con el mismo correo con el que te registraste al evento.",
    signInCta: "Iniciar sesión para canjear",
    claimCta: "Canjear créditos",
    claiming: "Canjeando…",
    signedInAs: "Sesión iniciada como {email}",
    yourCodes: "Tus códigos",
    alreadyRedeemed: "Ya canjeaste estos créditos para este evento.",
    copyCode: "Copiar",
    copied: "Copiado",
    invalidTitle: "Enlace no encontrado",
    invalidBody:
      "Este enlace de canje no es válido. Revisa la URL del organizador.",
    inactiveTitle: "Canje cerrado",
    inactiveBody: "Este evento ya no acepta canjes de créditos.",
    notEligibleTitle: "Correo no está en la lista",
    notEligibleBody:
      "El correo de tu sesión no está registrado en este evento. Usa el de tu registro en Luma.",
    soldOutTitle: "Códigos agotados",
    soldOutBody:
      "Todos los códigos de este evento ya fueron canjeados. Contacta al organizador.",
    noVerifiedEmailTitle: "Verifica tu correo",
    noVerifiedEmailBody:
      "Tu cuenta necesita un correo verificado antes de canjear créditos.",
    missingCodeTitle: "Falta el código",
    missingCodeBody: "Abre el enlace completo que incluye ?code=…",
    poolLabels: {
      CURSOR: "Cursor",
      CODEX: "Codex",
      OPENAI: "OpenAI Platform",
    },
    products: {
      cursor: {
        title: "Créditos de Cursor",
        blurb: "Canjea tu código de Cursor de este evento de Ai Labs.",
      },
      codex: {
        title: "Créditos de Codex",
        blurb: "Canjea tu código de Codex de este evento de Ai Labs.",
      },
      openai: {
        title: "Créditos de OpenAI Platform",
        blurb:
          "Canjea tu código de OpenAI Platform de este evento de Ai Labs.",
      },
      codexOpenai: {
        title: "Créditos de Codex + OpenAI Platform",
        blurb:
          "Canjea tus códigos de Codex y OpenAI Platform de este evento.",
      },
    },
  },
}
