/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as LocaleRedeemRouteImport } from './routes/$locale/redeem'
import { Route as LocaleApertureRouteImport } from './routes/$locale/aperture'
import { Route as LocaleAgenticRouteImport } from './routes/$locale/agentic'
import { Route as LocaleAcademyRouteImport } from './routes/$locale/academy'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRedeemRoute = LocaleRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleApertureRoute = LocaleApertureRouteImport.update({
  id: '/aperture',
  path: '/aperture',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAgenticRoute = LocaleAgenticRouteImport.update({
  id: '/agentic',
  path: '/agentic',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAcademyRoute = LocaleAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/academy': typeof LocaleAcademyRoute
  '/$locale/agentic': typeof LocaleAgenticRoute
  '/$locale/aperture': typeof LocaleApertureRoute
  '/$locale/redeem': typeof LocaleRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/academy': typeof LocaleAcademyRoute
  '/$locale/agentic': typeof LocaleAgenticRoute
  '/$locale/aperture': typeof LocaleApertureRoute
  '/$locale/redeem': typeof LocaleRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/academy': typeof LocaleAcademyRoute
  '/$locale/agentic': typeof LocaleAgenticRoute
  '/$locale/aperture': typeof LocaleApertureRoute
  '/$locale/redeem': typeof LocaleRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/academy'
    | '/$locale/agentic'
    | '/$locale/aperture'
    | '/$locale/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/academy'
    | '/$locale/agentic'
    | '/$locale/aperture'
    | '/$locale/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/academy'
    | '/$locale/agentic'
    | '/$locale/aperture'
    | '/$locale/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/redeem': {
      id: '/$locale/redeem'
      path: '/redeem'
      fullPath: '/$locale/redeem'
      preLoaderRoute: typeof LocaleRedeemRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/aperture': {
      id: '/$locale/aperture'
      path: '/aperture'
      fullPath: '/$locale/aperture'
      preLoaderRoute: typeof LocaleApertureRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/agentic': {
      id: '/$locale/agentic'
      path: '/agentic'
      fullPath: '/$locale/agentic'
      preLoaderRoute: typeof LocaleAgenticRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/academy': {
      id: '/$locale/academy'
      path: '/academy'
      fullPath: '/$locale/academy'
      preLoaderRoute: typeof LocaleAcademyRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAcademyRoute: typeof LocaleAcademyRoute
  LocaleAgenticRoute: typeof LocaleAgenticRoute
  LocaleApertureRoute: typeof LocaleApertureRoute
  LocaleRedeemRoute: typeof LocaleRedeemRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAcademyRoute: LocaleAcademyRoute,
  LocaleAgenticRoute: LocaleAgenticRoute,
  LocaleApertureRoute: LocaleApertureRoute,
  LocaleRedeemRoute: LocaleRedeemRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
